# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "customers", :force => true do |t|
    t.column "given_name",               :string
    t.column "sur_name",                 :string
    t.column "shipping_address_street",  :string
    t.column "shipping_address_postal",  :string
    t.column "shipping_address_zip",     :string
    t.column "shipping_address_country", :string
    t.column "billing_address_street",   :string
    t.column "billing_address_postal",   :string
    t.column "billing_address_zip",      :string
    t.column "billing_address_country",  :string
  end

  create_table "order_lines", :force => true do |t|
    t.column "order_id",   :integer
    t.column "product_id", :integer
    t.column "amount",     :integer
  end

  create_table "orders", :force => true do |t|
    t.column "customer_id", :integer
    t.column "time",        :datetime
    t.column "status",      :string
  end

  create_table "product_categories", :force => true do |t|
    t.column "product_type_id", :integer
    t.column "name",            :string
  end

  create_table "product_categories_products", :id => false, :force => true do |t|
    t.column "product_id",          :integer
    t.column "product_category_id", :integer
  end

  create_table "product_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "products", :force => true do |t|
    t.column "name",            :string
    t.column "description",     :text
    t.column "product_type_id", :integer
    t.column "price",           :integer
  end

  create_table "users", :force => true do |t|
    t.column "username", :string
    t.column "password", :string
  end

end
