# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: jdbc
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/liblib<%=LIBLIB_INSTANCE%>_dev
  username: liblib<%=LIBLIB_INSTANCE%>
  password: liblib<%=LIBLIB_INSTANCE%>

test:
  adapter: jdbc
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/liblib<%=LIBLIB_INSTANCE%>_test
  username: liblib<%=LIBLIB_INSTANCE%>
  password: liblib<%=LIBLIB_INSTANCE%>

production:
  adapter: jdbc
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/liblib<%=LIBLIB_INSTANCE%>_prod
  username: liblib<%=LIBLIB_INSTANCE%>
  password: liblib<%=LIBLIB_INSTANCE%>
